(()=>{
const TKEY='nwf-trash-v1';
const reasons=['채널 톤과 안 맞음','사진이 약함','화제성 부족','정치·사회성이 강함','이미 비슷한 소재를 다룸','오보·과장 우려','썸네일이 안 뽑힘'];
const trash=()=>{try{return JSON.parse(localStorage.getItem(TKEY))||[]}catch{return []}};
const saveTrash=v=>localStorage.setItem(TKEY,JSON.stringify(v));
function ensureTab(){const s=$('.segments');if(!s||s.querySelector('[data-filter="TRASH"]'))return;const b=document.createElement('button');b.dataset.filter='TRASH';b.textContent='TRASH';b.onclick=()=>{$$('.segments button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter='TRASH';renderRadar()};s.appendChild(b)}
function modal(){let m=$('#trashModal');if(m)return m;m=document.createElement('div');m.id='trashModal';m.className='trash-modal';m.innerHTML=`<div class="trash-dialog glass"><h3>TRASH로 이동</h3><p>왜 제외하는지 남겨주세요. 이 기록은 자동 추천 제외 기준으로 사용됩니다.</p><div class="trash-reasons">${reasons.map(r=>`<button type="button">${r}</button>`).join('')}</div><textarea id="trashMemo" placeholder="추가 메모"></textarea><div class="trash-actions"><button class="soft" id="trashCancel">취소</button><button class="primary" id="trashConfirm">휴지통으로 이동</button></div></div>`;document.body.appendChild(m);m.querySelectorAll('.trash-reasons button').forEach(b=>b.onclick=()=>b.classList.toggle('active'));$('#trashCancel').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}
let pending=null;
window.openTrash=function(id,e){e?.stopPropagation();const x=data.find(i=>i.id===id);if(!x)return;pending=id;const m=modal();m.querySelectorAll('.trash-reasons button').forEach(b=>b.classList.remove('active'));$('#trashMemo').value='';m.classList.add('open');$('#trashConfirm').onclick=()=>{const i=data.findIndex(v=>v.id===pending);if(i<0)return;const item=data.splice(i,1)[0],t=trash();t.unshift({...item,trashedAt:Date.now(),trashReasons:[...m.querySelectorAll('.trash-reasons button.active')].map(b=>b.textContent),trashMemo:$('#trashMemo').value.trim()});saveTrash(t);if(selected===item.id)selected=data.find(v=>v.status==='READY')?.id||data[0]?.id||'';persist();m.classList.remove('open');render();toast('TRASH로 이동했습니다')}};
window.restoreTrash=function(id,e){e?.stopPropagation();const t=trash(),i=t.findIndex(v=>v.id===id);if(i<0)return;const raw={...t.splice(i,1)[0]};delete raw.trashedAt;delete raw.trashReasons;delete raw.trashMemo;raw.status='READY';data.unshift(normalize([raw])[0]);saveTrash(t);selected=raw.id;filter='READY';persist();$$('.segments button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='READY'));render();toast('READY로 복구했습니다')};
const baseRadar=renderRadar;
renderRadar=function(){ensureTab();if(filter==='TRASH'){const t=trash();$('#radarList').innerHTML=t.length?t.map(x=>`<div class="radar-item trash-item"><div class="radar-row"><div class="score">×</div><div class="radar-copy"><div class="radar-title">${esc(x.title)}</div><div class="radar-meta">TRASH · ${esc(x.cat||'')}</div><div class="trash-note">${esc((x.trashReasons||[]).join(' · ')||'사유 없음')}${x.trashMemo?`<br>${esc(x.trashMemo)}`:''}</div><button class="restore-btn" onclick="restoreTrash('${x.id}',event)">다시 살리기</button></div></div></div>`).join(''):'<div class="empty-list">TRASH가 비어 있습니다</div>';return}baseRadar();if(filter==='READY'||filter==='ALL'){$$('#radarList .radar-item').forEach(card=>{const title=card.querySelector('.radar-title')?.textContent?.trim(),x=data.find(v=>v.title===title);if(!x||x.status!=='READY'||card.querySelector('.trash-hover'))return;card.style.position='relative';card.insertAdjacentHTML('beforeend',`<button class="trash-hover" title="TRASH로 이동" onclick="openTrash('${x.id}',event)" aria-label="휴지통"><svg viewBox="0 0 24 24"><path d="M9 3h6l1 2h4v2H4V5h4l1-2Zm-2 6h10l-1 11H8L7 9Zm3 2v7h2v-7h-2Zm4 0v7h2v-7h-2Z"/></svg></button>`)})}}
ensureTab();modal();renderRadar();
})();