(()=>{
function postedEvent(x){return x?.postedAt?{at:+x.postedAt,slides:Math.max(x.krSelected?.length||0,x.jpSelected?.length||0,1)}:null}
function formatTime(ts){const d=new Date(+ts),n=new Date(),same=d.toDateString()===n.toDateString();return same?`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`:`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function migrate(){data.forEach(x=>{if(x.status==='POSTED'&&!x.postedAt){x.postedAt=+x.postedKrAt||+x.postedJpAt||Date.now()}});persist()}
renderQuota=function(){const cutoff=Date.now()-14*864e5,c=data.filter(x=>x.postedAt&&+x.postedAt>=cutoff).length;$('#count14').textContent=c;$('#quotaBar').style.width=Math.min(100,c/150*100)+'%'};
const baseRadar=renderRadar;
renderRadar=function(){baseRadar();if(filter==='POSTED'){const list=data.filter(x=>x.status==='POSTED');$('#radarList').innerHTML=list.length?list.map(x=>`<div class="radar-item ${x.id===selected?'active':''}" onclick="selectItem('${x.id}')"><div class="radar-row"><div class="score">${x.score||28}</div><div class="radar-copy"><div class="radar-title">${esc(x.title)}</div><div class="radar-meta"><span class="dot POSTED"></span>POSTED · ${esc(x.cat||'해외토픽')}</div><div class="posted-meta"><span class="post-chip posted">POSTING · ${formatTime(x.postedAt)}</span></div></div></div></div>`).join(''):'<div class="empty-list">아직 POSTED 콘텐츠가 없습니다</div>'}}
function doPosting(){const x=current();if(!x)return;if(x.status==='POSTED'&&x.postedAt)return toast('이미 POSTED 처리된 콘텐츠입니다');x.status='POSTED';x.postedAt=Date.now();x.postLog=x.postLog||[];x.postLog.push({at:x.postedAt,type:'POSTING',kr:x.krSelected?.length||0,jp:x.jpSelected?.length||0});persist();renderQuota();if(filter==='READY'){const next=data.find(i=>i.status==='READY'&&i.id!==x.id);if(next)selected=next.id}render();toast('POSTED 이동 완료 · 14 DAYS +1')}
const baseStudio=renderStudio;
renderStudio=function(){baseStudio();const x=current(),root=$('#studio');if(!x||!root)return;let row=root.querySelector('.posting-action');if(!row){row=document.createElement('div');row.className='posting-action';const download=root.querySelector('.download-row');(download||root.lastElementChild)?.insertAdjacentElement('afterend',row)}row.innerHTML=x.status==='POSTED'?`<button class="posting-btn posted" disabled>POSTED · ${formatTime(x.postedAt)}</button>`:`<button class="posting-btn" onclick="window.markCurrentPosted()">POSTING</button><span>Instagram 업로드를 마쳤다면 눌러주세요. 이 순간 14 DAYS가 +1 됩니다.</span>`}
window.markCurrentPosted=doPosting;
changeStatus=function(v){if(v==='POSTED')return toast('POSTED는 아래 POSTING 버튼으로 처리하세요');const x=current();x.status=v;save()};
const basePublish=renderPublish;
renderPublish=function(){basePublish();const x=current();if(!x?.postedAt)return;$('#publish')?.insertAdjacentHTML('beforeend',`<div class="section posted-history"><div class="section-head"><b>POSTED HISTORY</b><span class="muted-small">${formatTime(x.postedAt)}</span></div><div class="guide">POSTING 버튼으로 게시 완료 처리된 콘텐츠입니다. KR ${x.krSelected?.length||0}장 · JP ${x.jpSelected?.length||0}장</div></div>`)};
migrate();render();
})();