(()=>{
const DB_NAME='nwf-media-v1',STORE='videos';
function db(){return new Promise((resolve,reject)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function putVideo(key,blob){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function getVideo(key){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(key);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)})}
function mediaById(id){return current()?.images?.find(i=>i.id===id)||null}
function activeLang(){return window.getFactoryLanguage?.()||localStorage.getItem('nwf-active-language-v1')||'kr'}
function activeReelMedia(){const x=current(),l=activeLang(),id=x?.reels?.[l]?.image;return mediaById(id)}
function isVideo(im){return !!im&&(im.type==='video-upload'||String(im.mime||'').startsWith('video/'))}
function fmtDuration(s){s=Math.max(0,Math.round(+s||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function posterFromVideo(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.muted=true;v.playsInline=true;v.src=url;let duration=0;const done=()=>{try{const c=document.createElement('canvas'),max=960,scale=Math.min(1,max/(v.videoWidth||max));c.width=Math.max(2,Math.round((v.videoWidth||720)*scale));c.height=Math.max(2,Math.round((v.videoHeight||1280)*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);const poster=c.toDataURL('image/jpeg',.78);URL.revokeObjectURL(url);resolve({poster,duration:duration||v.duration||0,width:v.videoWidth||0,height:v.videoHeight||0})}catch(e){URL.revokeObjectURL(url);reject(e)}};v.onloadedmetadata=()=>{duration=v.duration||0;const at=Math.min(Math.max(.1,duration*.08),1,Math.max(.1,duration-.05));if(Number.isFinite(at)&&duration>.12){v.currentTime=at}else done()};v.onseeked=done;v.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('video decode failed'))}})}
async function addVideo(file){toast('영상 분석 중…');const key=`video-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,id=`vid${Date.now()}${Math.random().toString(36).slice(2,5)}`;try{const meta=await posterFromVideo(file);await putVideo(key,file);const x=current();x.images=x.images||[];x.images.unshift({id,type:'video-upload',source:'upload',mediaKey:key,mime:file.type||'video/mp4',name:file.name,size:file.size,duration:meta.duration,width:meta.width,height:meta.height,url:meta.poster,display:meta.poster});if(x.images.length>10)x.images=x.images.slice(0,10);x.reels=x.reels||{};const l=activeLang();if(x.reels[l]){x.reels[l].image=id;x.reels[l].frame={z:1,x:0,y:0}}persist();renderStudio();renderPublish();toast(`영상 업로드 완료 · ${fmtDuration(meta.duration)}`)}catch(e){console.error(e);toast('영상을 읽지 못했습니다 · MP4(H.264) 파일인지 확인해주세요')}}
async function addImage(file){const r=new FileReader;r.onload=()=>{const x=current(),id='up'+Date.now(),url=r.result;x.images.unshift({id,url,display:url,source:'upload',type:'image-upload',name:file.name,mime:file.type});if(x.images.length>10)x.images=x.images.slice(0,10);persist();renderStudio();toast('업로드 이미지가 후보에 추가됐습니다')};r.readAsDataURL(file)}
function replaceInput(){const old=document.getElementById('fileInput');if(!old)return;const n=old.cloneNode(false);n.accept='image/*,video/*';n.value='';old.replaceWith(n);n.addEventListener('change',async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(String(f.type||'').startsWith('video/'))await addVideo(f);else if(String(f.type||'').startsWith('image/'))await addImage(f);else toast('이미지 또는 영상 파일만 업로드할 수 있습니다')});window.pickFile=()=>n.click()}
async function videoUrl(im){if(!isVideo(im)||!im.mediaKey)return null;const blob=await getVideo(im.mediaKey);return blob?URL.createObjectURL(blob):null}
async function captureCurrentFrame(){const v=document.getElementById('reelVideoPlayer'),im=activeReelMedia();if(!v||!im||!isVideo(im)||!v.videoWidth)return toast('영상이 재생 가능한 상태인지 확인해주세요');const c=document.createElement('canvas'),max=960,scale=Math.min(1,max/v.videoWidth);c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);c.getContext('2d').drawImage(v,0,0,c.width,c.height);const poster=c.toDataURL('image/jpeg',.8);im.url=poster;im.display=poster;im.posterTime=v.currentTime||0;persist();renderStudio();toast(`현재 ${v.currentTime.toFixed(1)}초 프레임을 커버로 저장했습니다`)}
window.captureCurrentVideoFrame=captureCurrentFrame;
async function enhanceVideoPreview(){const wrap=document.querySelector('.reel-preview');if(!wrap)return;const im=activeReelMedia();document.querySelectorAll('.reel-candidate').forEach(b=>{const img=b.querySelector('img'),src=img?.getAttribute('src')||'';const m=current()?.images?.find(x=>(x.display||x.url)===src);if(isVideo(m)&&!b.querySelector('.video-upload-badge'))b.insertAdjacentHTML('beforeend','<em class="video-upload-badge">VIDEO</em>')});if(!isVideo(im))return;const canvas=wrap.querySelector('#reelCanvas');if(canvas)canvas.classList.add('video-cover-canvas');if(wrap.querySelector('.video-player-box'))return;const box=document.createElement('div');box.className='video-player-box';box.innerHTML=`<div class="video-player-head"><b>업로드 영상</b><span>${esc(im.name||'MP4')} · ${fmtDuration(im.duration)}</span></div><video id="reelVideoPlayer" controls playsinline preload="metadata" poster="${esc(im.display||im.url||'')}"></video><div class="video-player-actions"><button class="soft" onclick="captureCurrentVideoFrame()">현재 프레임을 커버로</button><span>아래 9:16 캔버스는 Instagram 릴스 커버 저장용입니다.</span></div>`;wrap.insertBefore(box,wrap.firstChild);try{const u=await videoUrl(im);const v=box.querySelector('video');if(u){v.src=u;v.dataset.objectUrl=u;v.addEventListener('ended',()=>{v.currentTime=0});}}catch(e){console.warn('video load',e)}}
function markCarouselVideoPosters(){document.querySelectorAll('.candidate').forEach(card=>{const img=card.querySelector('img'),src=img?.getAttribute('src')||'',im=current()?.images?.find(x=>(x.display||x.url)===src);if(isVideo(im)){const badge=card.querySelector('.candidate-badge');if(badge)badge.textContent='VIDEO FRAME';card.title='캐러셀에서는 영상 자체가 아니라 추출된 정지 프레임을 사용합니다.'}})}
const studioBeforeVideo=renderStudio;renderStudio=function(){studioBeforeVideo();requestAnimationFrame(()=>{enhanceVideoPreview();markCarouselVideoPosters()})};
const setReelBeforeVideo=window.setReelImage;window.setReelImage=function(l,id){setReelBeforeVideo(l,id);requestAnimationFrame(enhanceVideoPreview)};
window.NWVideoStore={getVideo,putVideo};
replaceInput();requestAnimationFrame(()=>{enhanceVideoPreview();markCarouselVideoPosters()});
})();