const DEFAULTS=[
{id:'bolt',title:'우사인 볼트가 13년 연인에게 프러포즈한 순간',score:29,cat:'해외연예',status:'READY',source:'https://www.justjared.com/2026/08/22/usain-bolt-proposes-to-longtime-girlfriend-kasi-bennett-at-his-40th-birthday-celebration/',hooksKr:['13년 만에\n무릎 꿇었다','마침내\n반지를 꺼냈다','세계에서 가장\n빠른 남자'],hooksJp:['13年越しに\nひざまずいた','ついに\n指輪を取り出した','世界最速の\n男'],hook:0,headlineKr:'13년 만에\n무릎 꿇었다',headlineJp:'13年越しに\nひざまずいた',captionKr:'우사인 볼트가 13년을 함께한 연인 카시 베넷에게 프러포즈했습니다.\n\n40번째 생일 파티에서 무릎을 꿇고 반지를 건넨 장면이 공개되며 화제가 됐습니다.\n\n#NOWAYTHIS #해외연예 #우사인볼트',captionJp:'ウサイン・ボルトが13年間交際したカシ・ベネットにプロポーズしました。\n\n40歳の誕生日パーティーでひざまずき、指輪を渡す場面が話題になっています。\n\n#海外エンタメ #NOWAYTHIS',music:['Perfect','Until I Found You','A Thousand Years'],fact:['원본 사진·영상 출처 확인','사건 날짜 확인','약혼과 결혼 표현 구분'],done:[],images:[],krImage:null,jpImage:null,krFrame:{z:1,x:0,y:0},jpFrame:{z:1,x:0,y:0}},
{id:'kinkajou',title:'텍사스 쇼핑센터에서 발견된 정체불명 동물',score:28,cat:'동물',status:'READY',source:'https://people.com/mysterious-animal-found-in-texas-strip-mall-was-actually-a-kinkajou-11794857/',hooksKr:['이 동물의\n정체는?','경찰도\n처음엔 몰랐다','캥거루?\n원숭이?'],hooksJp:['この動物の\n正体は？','警察も\n最初は分からず','カンガルー？\nサル？'],hook:0,headlineKr:'이 동물의\n정체는?',headlineJp:'この動物の\n正体は？',captionKr:'미국 텍사스 쇼핑센터에서 정체불명의 동물이 발견됐습니다.\n\n정체는 중남미 열대우림에 사는 킨카주였습니다.\n\n#NOWAYTHIS #해외토픽 #희귀동물',captionJp:'アメリカ・テキサスのショッピングセンターで謎の動物が発見されました。\n\n正体はキンカジューでした。\n\n#海外ニュース #NOWAYTHIS',music:['Mystery of Love','Curious','original audio'],fact:['공식 발표 확인','동물 종 확인','소유 관계 단정 금지'],done:[],images:[],krImage:null,jpImage:null,krFrame:{z:1,x:0,y:0},jpFrame:{z:1,x:0,y:0}}
];
const KEY='nwf-production-v1',SEL='nwf-production-selected';
let data=normalize(load()||DEFAULTS),selected=localStorage.getItem(SEL)||data[0].id,filter='ALL',drag=null;const runtime={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function normalize(a){return a.map(x=>({...x,images:x.images||[],done:x.done||[],krFrame:x.krFrame||{z:1,x:0,y:0},jpFrame:x.jpFrame||{z:1,x:0,y:0},headlineKr:x.headlineKr||x.hooksKr?.[0]||'',headlineJp:x.headlineJp||x.hooksJp?.[0]||''}))}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem(SEL,selected)}catch(e){console.warn(e)}}
function cur(){return data.find(x=>x.id===selected)||data[0]}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){renderQuota();renderRadar();renderStudio();renderPublish()}
function renderQuota(){const cutoff=Date.now()-14*864e5,n=data.filter(x=>x.status==='POSTED'&&x.postedAt>=cutoff).length;$('#count14').textContent=n;$('#quotaBar').style.width=Math.min(100,n/150*100)+'%'}
function renderRadar(){const a=data.filter(x=>filter==='ALL'||x.status===filter);$('#radarList').innerHTML=a.map(x=>`<div class="radar-item ${x.id===selected?'active':''}" data-id="${x.id}"><div class="radar-row"><div class="score">${x.score}</div><div><div class="radar-title">${esc(x.title)}</div><div class="radar-meta"><span class="dot ${x.status}"></span>${x.status} · ${esc(x.cat||'해외토픽')}</div></div></div></div>`).join('')||'<div class="hero-empty">비어 있습니다.</div>';$$('.radar-item').forEach(el=>el.onclick=()=>select(el.dataset.id))}
function select(id){selected=id;persist();render();autoImages()}
function renderStudio(){const x=cur();$('#imageCount').textContent=`AUTO · ${x.images.length}/10 IMAGES`;$('#studio').innerHTML=`<div class="hero"><div><h2>${esc(x.title)}</h2><p>${esc(x.cat||'해외토픽')} · viral score ${x.score}/30</p></div><select class="status" id="status"><option ${x.status==='READY'?'selected':''}>READY</option><option ${x.status==='HOLD'?'selected':''}>HOLD</option><option ${x.status==='POSTED'?'selected':''}>POSTED</option></select></div><div class="source-box"><div class="source-row"><input class="source-input" id="source" value="${esc(x.source||'')}" placeholder="기사·원본 URL"><button class="primary" id="searchImages">이미지 10장 찾기</button><button class="soft" id="upload">업로드</button></div><div class="source-hint">기사 본문 이미지 → 대표 이미지 → 제목·본문 관련 이미지 순으로 최대 10장을 수집합니다.</div><div class="hero-image">${heroImageHTML(x)}</div><div class="candidate-grid">${candidateHTML(x)}</div></div><div class="preview-grid"><div class="card"><span class="lang">KR</span><span class="drag-tip">drag · wheel</span><canvas id="kr"></canvas></div><div class="card"><span class="lang">JP</span><span class="drag-tip">drag · wheel</span><canvas id="jp"></canvas></div></div><div class="eyebrow">Headline</div><div class="hook-row">${x.hooksKr.map((h,i)=>`<button data-hook="${i}" class="${i===x.hook?'active':''}">${esc(h.replace(/\n/g,' / '))}</button>`).join('')}</div><div class="headline-grid"><textarea class="headline" id="headlineKr" placeholder="Enter로 줄바꿈">${esc(x.headlineKr)}</textarea><textarea class="headline" id="headlineJp" placeholder="Enterで改行">${esc(x.headlineJp)}</textarea></div><div class="download-row"><button class="soft" data-download="kr">KR 저장</button><button class="soft" data-download="jp">JP 저장</button></div>`;
$('#status').onchange=e=>{x.status=e.target.value;if(x.status==='POSTED')x.postedAt=Date.now();persist();renderQuota();renderRadar();renderPublish()};$('#source').onchange=e=>{x.source=e.target.value.trim();persist()};$('#searchImages').onclick=()=>findImages(true);$('#upload').onclick=()=>$('#fileInput').click();$$('[data-hook]').forEach(b=>b.onclick=()=>setHook(+b.dataset.hook));$('#headlineKr').oninput=e=>{x.headlineKr=e.target.value;persist();draw('kr')};$('#headlineJp').oninput=e=>{x.headlineJp=e.target.value;persist();draw('jp')};$$('[data-download]').forEach(b=>b.onclick=()=>download(b.dataset.download));bindCandidates();requestAnimationFrame(()=>{draw('kr');draw('jp');bindCanvas('kr');bindCanvas('jp')})}
function heroImageHTML(x){const id=x.krImage||x.jpImage||x.images[0]?.id,im=x.images.find(v=>v.id===id)||x.images[0];return im?`<img src="${esc(im.display||im.url)}" alt="실제 사진 후보">`:'<div class="hero-empty">관련 실제 사진을 자동으로 찾습니다.</div>'}
function candidateHTML(x){if(!x.images.length)return '<div class="hero-empty" style="grid-column:1/-1;height:90px">후보가 아직 없습니다.</div>';return x.images.slice(0,10).map(im=>`<div class="candidate" data-origin="${esc(im.origin||im.url)}"><img src="${esc(im.display||im.url)}" alt=""><span class="candidate-badge">${esc(im.kind||'WEB')}</span><div class="candidate-actions"><button data-lang="kr" data-image="${im.id}" class="${x.krImage===im.id?'selected':''}">KR</button><button data-lang="jp" data-image="${im.id}" class="${x.jpImage===im.id?'selected':''}">JP</button></div></div>`).join('')}
function bindCandidates(){$$('.candidate-actions button').forEach(b=>b.onclick=e=>{e.stopPropagation();assign(b.dataset.lang,b.dataset.image)});$$('.candidate').forEach(c=>c.onclick=()=>{const u=c.dataset.origin;if(u&&/^https?:/.test(u))window.open(u,'_blank','noopener')})}
function assign(lang,id){const x=cur();if(lang==='kr'){x.krImage=id;x.krFrame={z:1,x:0,y:0}}else{x.jpImage=id;x.jpFrame={z:1,x:0,y:0}}persist();renderStudio()}
function setHook(i){const x=cur();x.hook=i;x.headlineKr=x.hooksKr[i]||x.headlineKr;x.headlineJp=x.hooksJp[i]||x.headlineJp;persist();renderStudio()}
function renderPublish(){const x=cur();$('#publishState').textContent=x.status;$('#publish').innerHTML=`<div class="section"><div class="section-head"><b>KR CAPTION</b><button class="tiny" data-copy="kr">복사</button></div><textarea class="caption" id="capKr">${esc(x.captionKr||'')}</textarea></div><div class="section"><div class="section-head"><b>JP CAPTION</b><button class="tiny" data-copy="jp">コピー</button></div><textarea class="caption" id="capJp">${esc(x.captionJp||'')}</textarea></div><div class="section"><div class="section-head"><b>INSTAGRAM MUSIC</b><span style="font-size:11px;color:var(--muted)">앱에서 선택</span></div>${(x.music||[]).map(m=>`<div class="music"><span>${esc(m)}</span><button class="tiny" data-music="${esc(m)}">복사</button></div>`).join('')}</div><div class="section"><div class="section-head"><b>FACT CHECK</b></div><div class="checks">${(x.fact||[]).map((f,i)=>`<label><input type="checkbox" data-check="${i}" ${x.done[i]?'checked':''}>${esc(f)}</label>`).join('')}</div></div><div class="section"><div class="section-head"><b>POST GUIDE</b></div><div class="guide">KR/JP 이미지 저장 → Instagram 앱에서 사진 선택 → 추천 음원 추가 → 캡션 붙여넣기 → 게시 후 상태를 POSTED로 변경</div></div>`;$('#capKr').oninput=e=>{x.captionKr=e.target.value;persist()};$('#capJp').oninput=e=>{x.captionJp=e.target.value;persist()};$$('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy==='kr'?x.captionKr:x.captionJp,'캡션 복사'));$$('[data-music]').forEach(b=>b.onclick=()=>copy(b.dataset.music,'음원명 복사'));$$('[data-check]').forEach(c=>c.onchange=()=>{x.done[+c.dataset.check]=c.checked;persist()})}
function copy(t,msg){navigator.clipboard.writeText(t||'');toast(msg)}
function searchQuery(x){return [x.title,(x.captionKr||'').split('\n').slice(0,2).join(' ')].join(' ').replace(/[#@]/g,' ').slice(0,240)}
function proxy(u){if(!u||u.startsWith('data:')||u.includes('images.weserv.nl'))return u;return 'https://images.weserv.nl/?url='+encodeURIComponent(u.replace(/^https?:\/\//,''))+'&w=1600&h=2000&fit=inside&output=jpg'}
function addFound(arr,u,kind){if(!u||!/^https?:\/\//i.test(u))return;u=u.replace(/&amp;/g,'&');if(/\.svg($|\?)/i.test(u))return;if(arr.some(v=>v.origin===u))return;arr.push({id:'im'+Date.now()+Math.random().toString(36).slice(2),origin:u,url:proxy(u),display:proxy(u),kind})}
async function articleImages(url,arr){if(!url)return;try{const r=await fetch('https://r.jina.ai/'+url,{headers:{Accept:'text/plain'}});if(!r.ok)return;const t=await r.text();let m;const md=/!\[[^\]]*\]\((https?:\/\/[^)\s]+)[^)]*\)/g;while((m=md.exec(t))&&arr.length<10)addFound(arr,m[1],'ARTICLE');const raw=/https?:\/\/[^\s)"']+\.(?:jpg|jpeg|png|webp)(?:\?[^\s)"']*)?/gi;while((m=raw.exec(t))&&arr.length<10)addFound(arr,m[0],'ARTICLE')}catch(e){console.warn('reader',e)}}
async function ogImage(url,arr){if(!url||arr.length>=10)return;try{const r=await fetch('https://api.microlink.io/?url='+encodeURIComponent(url));const j=await r.json();addFound(arr,j?.data?.image?.url,'OG')}catch(e){console.warn('og',e)}}
async function openverseImages(x,arr){if(arr.length>=10)return;try{const n=10-arr.length,r=await fetch('https://api.openverse.org/v1/images/?q='+encodeURIComponent(searchQuery(x))+'&page_size='+n),j=await r.json();(j.results||[]).forEach(it=>addFound(arr,it.thumbnail||it.url,'RELATED'))}catch(e){console.warn('openverse',e)}}
async function findImages(manual=false){const x=cur(),btn=$('#searchImages');if(btn){btn.disabled=true;btn.textContent='찾는 중'}x.source=$('#source')?.value.trim()||x.source;persist();const arr=[];await articleImages(x.source,arr);await ogImage(x.source,arr);await openverseImages(x,arr);x.images=arr.slice(0,10);x.krImage=x.images[0]?.id||null;x.jpImage=x.images[1]?.id||x.images[0]?.id||null;x.krFrame={z:1,x:0,y:0};x.jpFrame={z:1,x:0,y:0};persist();renderStudio();toast(x.images.length?`${x.images.length}장 불러옴`:'자동 탐색 실패 · 업로드 사용');}
async function autoImages(){const x=cur();if(x.images.length>=6)return;await findImages(false)}
$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const x=cur(),id='up'+Date.now(),im={id,origin:'',url:r.result,display:r.result,kind:'UPLOAD'};runtime[id]=r.result;x.images.unshift(im);x.images=x.images.slice(0,10);x.krImage=x.krImage||id;x.jpImage=x.jpImage||id;persist();renderStudio();toast('업로드 완료')};r.readAsDataURL(f);e.target.value=''}
async function getImg(id){const x=cur(),it=x.images.find(v=>v.id===id);if(!it)return null;if(runtime[id] instanceof Image)return runtime[id];return new Promise(res=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>{runtime[id]=im;res(im)};im.onerror=()=>res(null);im.src=it.display||it.url})}
function cover(ctx,im,w,h,f){const s=Math.max(w/im.width,h/im.height)*f.z,nw=im.width*s,nh=im.height*s;ctx.drawImage(im,(w-nw)/2+f.x,(h-nh)/2+f.y,nw,nh)}
async function draw(lang){const c=$('#'+lang);if(!c)return;c.width=1080;c.height=1350;const ctx=c.getContext('2d'),x=cur(),id=lang==='kr'?x.krImage:x.jpImage,f=lang==='kr'?x.krFrame:x.jpFrame,im=await getImg(id);ctx.fillStyle='#17191c';ctx.fillRect(0,0,1080,1350);if(im)cover(ctx,im,1080,1350,f);else{ctx.fillStyle='#32363b';ctx.font='600 30px -apple-system,sans-serif';ctx.textAlign='center';ctx.fillStyle='rgba(255,255,255,.5)';ctx.fillText('이미지를 선택하세요',540,675)}const g=ctx.createLinearGradient(0,670,0,1350);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.42,'rgba(0,0,0,.30)');g.addColorStop(1,'rgba(0,0,0,.90)');ctx.fillStyle=g;ctx.fillRect(0,650,1080,700);ctx.textAlign='left';ctx.fillStyle='#fff';ctx.shadowColor='rgba(0,0,0,.65)';ctx.shadowBlur=18;ctx.font='900 70px -apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif';multiline(ctx,lang==='kr'?x.headlineKr:x.headlineJp,72,920,930,84,4);ctx.shadowBlur=0;ctx.font='800 27px -apple-system,sans-serif';ctx.fillText('NO WAY THIS',72,1245)}
function multiline(ctx,text,x,y,maxW,lh,max){const lines=[];String(text||'').split('\n').forEach(p=>{if(!p.trim()){lines.push('');return}const parts=p.includes(' ')?p.split(' '):[...p];let line='';parts.forEach(w=>{const t=line?(p.includes(' ')?line+' '+w:line+w):w;if(ctx.measureText(t).width>maxW&&line){lines.push(line);line=w}else line=t});if(line)lines.push(line)});lines.slice(0,max).forEach((l,i)=>ctx.fillText(l,x,y+i*lh))}
function bindCanvas(lang){const c=$('#'+lang);if(!c||c.dataset.bound)return;c.dataset.bound='1';c.onpointerdown=e=>{drag={lang,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag||drag.lang!==lang)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;const f=lang==='kr'?cur().krFrame:cur().jpFrame;f.x+=dx*(1080/c.clientWidth);f.y+=dy*(1350/c.clientHeight);persist();draw(lang)};c.onpointerup=c.onpointerleave=()=>drag=null;c.onwheel=e=>{e.preventDefault();const f=lang==='kr'?cur().krFrame:cur().jpFrame;f.z=Math.max(.8,Math.min(3,f.z+(e.deltaY<0?.08:-.08)));persist();draw(lang)}}
function download(lang){const c=$('#'+lang);try{const a=document.createElement('a');a.download=`noway_${cur().id}_${lang}.png`;a.href=c.toDataURL('image/png');a.click()}catch(e){toast('저장 실패 · 다른 후보 이미지를 선택하세요')}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
$('#addBtn').onclick=()=>$('#modal').classList.add('open');$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};$('#saveNew').onclick=()=>{const title=$('#newTitle').value.trim();if(!title)return toast('제목을 입력하세요');const id='n'+Date.now(),kr=$('#newKr').value.trim()||title,jp=$('#newJp').value.trim()||kr;data.unshift({id,title,score:28,cat:'해외토픽',status:'HOLD',source:$('#newSource').value.trim(),hooksKr:[kr,'',''],hooksJp:[jp,'',''],hook:0,headlineKr:kr,headlineJp:jp,captionKr:$('#newCapKr').value,captionJp:$('#newCapJp').value,music:['추천 음원 입력 필요','original audio'],fact:['원본 출처 확인','날짜 확인','핵심 사실 확인'],done:[],images:[],krImage:null,jpImage:null,krFrame:{z:1,x:0,y:0},jpFrame:{z:1,x:0,y:0}});selected=id;persist();$('#modal').classList.remove('open');render();autoImages()};
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(v=>v.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderRadar()});
render();autoImages();
