const DEFAULTS=[
{id:'bolt',title:'우사인 볼트가 13년 연인에게 프러포즈한 순간',score:29,cat:'해외연예',status:'READY',source:'https://www.justjared.com/2026/08/22/usain-bolt-proposes-to-longtime-girlfriend-kasi-bennett-at-his-40th-birthday-celebration/',hooksKr:['13년 만에\n무릎 꿇었다','마침내\n반지를 꺼냈다','세계에서 가장\n빠른 남자'],hooksJp:['13年越しに\nひざまずいた','ついに\n指輪を取り出した','世界最速の\n男'],hook:0,headlineKr:'13년 만에\n무릎 꿇었다',headlineJp:'13年越しに\nひざまずいた',captionKr:'우사인 볼트가 13년을 함께한 연인 카시 베넷에게 프러포즈했습니다.\n\n40번째 생일 파티에서 무릎을 꿇고 반지를 건넨 장면이 공개되며 화제가 됐습니다.\n\n#NOWAYTHIS #해외연예 #우사인볼트',captionJp:'ウサイン・ボルトが13年間交際したカシ・ベネットにプロポーズしました。\n\n40歳の誕生日パーティーでひざまずき、指輪を渡す場面が話題になっています。\n\n#海外エンタメ #NOWAYTHIS',music:['Perfect','Until I Found You','A Thousand Years'],fact:['원본 사진·영상 출처 확인','사건 날짜 확인','약혼과 결혼 표현 구분'],done:[],images:[]},
{id:'kinkajou',title:'텍사스 쇼핑센터에서 발견된 정체불명 동물',score:28,cat:'동물',status:'READY',source:'https://people.com/mysterious-animal-found-in-texas-strip-mall-was-actually-a-kinkajou-11794857/',hooksKr:['이 동물의\n정체는?','경찰도\n처음엔 몰랐다','캥거루?\n원숭이?'],hooksJp:['この動物の\n正体は？','警察も\n最初は分からず','カンガルー？\nサル？'],hook:0,headlineKr:'이 동물의\n정체는?',headlineJp:'この動物の\n正体は？',captionKr:'미국 텍사스 쇼핑센터에서 정체불명의 동물이 발견됐습니다.\n\n정체는 중남미 열대우림에 사는 킨카주였습니다.\n\n#NOWAYTHIS #해외토픽 #희귀동물',captionJp:'アメリカ・テキサスのショッピングセンターで謎の動物が発見されました。\n\n正体はキンカジューでした。\n\n#海外ニュース #NOWAYTHIS',music:['Mystery of Love','Curious','original audio'],fact:['공식 발표 확인','동물 종 확인','소유 관계 단정 금지'],done:[],images:[]}
];
const KEY='nwf-production-v1',SEL='nwf-production-selected';
let data=normalize(load()||DEFAULTS),selected=localStorage.getItem(SEL)||data[0]?.id,filter='ALL',drag=null;const runtime={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function normalize(arr){return arr.map(x=>{const ids=(x.images||[]).map(i=>i.id),oldKr=x.krImage?[x.krImage]:[],oldJp=x.jpImage?[x.jpImage]:[],krSelected=(x.krSelected||oldKr).filter(id=>ids.includes(id)),jpSelected=(x.jpSelected||oldJp).filter(id=>ids.includes(id)),krFrames=x.krFrames||{},jpFrames=x.jpFrames||{};if(x.krImage&&x.krFrame)krFrames[x.krImage]=x.krFrame;if(x.jpImage&&x.jpFrame)jpFrames[x.jpImage]=x.jpFrame;return {...x,images:x.images||[],done:x.done||[],hook:x.hook||0,headlineKr:x.headlineKr||x.hooksKr?.[x.hook||0]||'',headlineJp:x.headlineJp||x.hooksJp?.[x.hook||0]||'',krSelected,jpSelected,krActive:x.krActive||krSelected[0]||null,jpActive:x.jpActive||jpSelected[0]||null,krFrames,jpFrames,krFontSize:+x.krFontSize||70,jpFontSize:+x.jpFontSize||70,textModeKr:x.textModeKr||'all',textModeJp:x.textModeJp||'all'}})}
function current(){return data.find(x=>x.id===selected)||data[0]}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem(SEL,selected)}
function save(){persist();render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function render(){renderQuota();renderRadar();renderStudio();renderPublish()}
function renderQuota(){const cutoff=Date.now()-14*864e5,c=data.filter(x=>x.status==='POSTED'&&x.postedAt>=cutoff).length;$('#count14').textContent=c;$('#quotaBar').style.width=Math.min(100,c/150*100)+'%'}
function renderRadar(){const a=data.filter(x=>filter==='ALL'||x.status===filter);$('#radarList').innerHTML=a.length?a.map(x=>`<div class="radar-item ${x.id===selected?'active':''}" onclick="selectItem('${x.id}')"><div class="radar-row"><div class="score">${x.score||28}</div><div><div class="radar-title">${esc(x.title)}</div><div class="radar-meta"><span class="dot ${x.status}"></span>${x.status} · ${esc(x.cat||'해외토픽')}</div></div></div></div>`).join(''):'<div class="empty-list">비어 있습니다</div>'}
function selectItem(id){selected=id;save();autoFindImages()}
function renderStudio(){const x=current();if(!x){$('#studio').innerHTML='';return}$('#imageCount').textContent=`${x.images.length} IMAGES · KR ${x.krSelected.length} · JP ${x.jpSelected.length}`;$('#studio').innerHTML=`<div class="hero"><div><h2>${esc(x.title)}</h2><p>${esc(x.cat||'해외토픽')} · viral score ${x.score||28}/30</p></div><select class="status" onchange="changeStatus(this.value)"><option ${x.status==='READY'?'selected':''}>READY</option><option ${x.status==='HOLD'?'selected':''}>HOLD</option><option ${x.status==='POSTED'?'selected':''}>POSTED</option></select></div><div class="source-box"><div class="source-row"><input id="sourceInput" class="source-input" value="${esc(x.source||'')}" placeholder="기사·원본 URL"><button id="findBtn" class="primary" onclick="findImages(true)">이미지 10장 찾기</button><button class="soft" onclick="pickFile()">업로드</button></div><div class="source-hint">후보에서 KR/JP 버튼을 각각 눌러 1~10장을 자유롭게 선택하세요. 다시 누르면 선택 해제됩니다.</div><div class="candidate-grid">${candidateHtml(x)}</div></div><div class="preview-grid">${previewPane(x,'kr')}${previewPane(x,'jp')}</div><div class="eyebrow">Headline</div><div class="hook-row">${x.hooksKr.map((h,i)=>`<button class="${i===x.hook?'active':''}" onclick="setHook(${i})">${esc(h.replace(/\n/g,' / '))}</button>`).join('')}</div><div class="headline-grid"><div><textarea class="headline" oninput="editHeadline('kr',this.value)" placeholder="KR · Enter로 줄바꿈">${esc(x.headlineKr)}</textarea>${fontControl(x,'kr')}</div><div><textarea class="headline" oninput="editHeadline('jp',this.value)" placeholder="JP · Enterで改行">${esc(x.headlineJp)}</textarea>${fontControl(x,'jp')}</div></div><div class="download-row"><button class="soft" onclick="downloadSelected('kr')">KR ${x.krSelected.length}장 저장</button><button class="soft" onclick="downloadSelected('jp')">JP ${x.jpSelected.length}장 저장</button></div>`;requestAnimationFrame(()=>{drawAll();bindCanvas('kr');bindCanvas('jp')})}
function candidateHtml(x){if(!x.images.length)return '<div class="candidate candidate-empty">이미지를 찾는 중입니다</div>';return x.images.slice(0,10).map((im,i)=>`<div class="candidate"><img src="${esc(im.display||im.url)}" alt="후보 ${i+1}"><span class="candidate-badge">${i+1}</span><div class="candidate-actions"><button class="${x.krSelected.includes(im.id)?'selected':''}" onclick="toggleSelect('kr','${im.id}')">KR</button><button class="${x.jpSelected.includes(im.id)?'selected':''}" onclick="toggleSelect('jp','${im.id}')">JP</button></div></div>`).join('')}
function previewPane(x,lang){const selectedIds=lang==='kr'?x.krSelected:x.jpSelected,active=lang==='kr'?x.krActive:x.jpActive,label=lang.toUpperCase();return `<div class="preview-unit"><div class="selection-head"><div><b>${label}</b><span>${selectedIds.length}장 선택</span></div><div class="slide-count">${active?selectedIds.indexOf(active)+1:0}/${selectedIds.length}</div></div><div class="card"><span class="lang">${label}</span><span class="drag-tip">drag · wheel</span><canvas id="${lang}"></canvas></div><div class="selected-strip">${selectedIds.length?selectedIds.map((id,i)=>{const im=x.images.find(a=>a.id===id);return im?`<button class="slide-thumb ${id===active?'active':''}" onclick="activateSlide('${lang}','${id}')"><img src="${esc(im.display||im.url)}"><span>${i+1}</span></button>`:''}).join(''):'<div class="no-selection">후보에서 '+label+' 이미지를 선택하세요</div>'}</div></div>`}
function fontControl(x,lang){const val=lang==='kr'?x.krFontSize:x.jpFontSize;return `<div class="font-control"><span>${lang.toUpperCase()} 글자 크기</span><input type="range" min="42" max="110" step="2" value="${val}" oninput="setFontSize('${lang}',this.value,this.nextElementSibling)"><output>${val}px</output></div>`}
function renderPublish(){const x=current();if(!x){$('#publish').innerHTML='';return}$('#publishState').textContent=x.status;$('#publish').innerHTML=`<div class="section"><div class="section-head"><b>KR CAPTION</b><button class="tiny" onclick="copyCaption('kr')">복사</button></div><textarea class="caption" oninput="editCaption('kr',this.value)">${esc(x.captionKr||'')}</textarea></div><div class="section"><div class="section-head"><b>JP CAPTION</b><button class="tiny" onclick="copyCaption('jp')">コピー</button></div><textarea class="caption" oninput="editCaption('jp',this.value)">${esc(x.captionJp||'')}</textarea></div><div class="section"><div class="section-head"><b>INSTAGRAM MUSIC</b><span class="muted-small">앱에서 선택</span></div>${(x.music||[]).map(m=>`<div class="music"><span>${esc(m)}</span><button class="tiny" onclick="copyInline('${esc(m).replace(/'/g,"\\'")}')">복사</button></div>`).join('')}</div><div class="section"><div class="section-head"><b>FACT CHECK</b></div><div class="checks">${(x.fact||[]).map((f,i)=>`<label><input type="checkbox" ${x.done[i]?'checked':''} onchange="toggleFact(${i},this.checked)">${esc(f)}</label>`).join('')}</div></div><div class="section"><div class="section-head"><b>CAROUSEL</b></div><div class="guide">KR ${x.krSelected.length}장 · JP ${x.jpSelected.length}장 선택됨<br>각 언어의 썸네일 스트립을 눌러 사진별 크롭을 수정할 수 있습니다.<br>저장 버튼은 현재 선택된 장수만큼 순서대로 PNG를 생성합니다.</div></div>`}
function changeStatus(v){const x=current();x.status=v;if(v==='POSTED')x.postedAt=Date.now();save()}
function setHook(i){const x=current();x.hook=i;x.headlineKr=x.hooksKr[i]||x.headlineKr;x.headlineJp=x.hooksJp[i]||x.headlineJp;save()}
function editHeadline(lang,v){const x=current();if(lang==='kr')x.headlineKr=v;else x.headlineJp=v;persist();draw(lang)}
function setFontSize(lang,v,out){const x=current(),n=+v;if(lang==='kr')x.krFontSize=n;else x.jpFontSize=n;if(out)out.textContent=n+'px';persist();draw(lang)}
function editCaption(lang,v){const x=current();if(lang==='kr')x.captionKr=v;else x.captionJp=v;persist()}
function copyCaption(lang){navigator.clipboard.writeText(lang==='kr'?current().captionKr:current().captionJp);toast('캡션 복사 완료')}
function copyInline(t){navigator.clipboard.writeText(t);toast('복사 완료')}
function toggleFact(i,v){current().done[i]=v;persist()}
function toggleSelect(lang,id){const x=current(),key=lang==='kr'?'krSelected':'jpSelected',activeKey=lang==='kr'?'krActive':'jpActive',arr=x[key],idx=arr.indexOf(id);if(idx>=0){arr.splice(idx,1);if(x[activeKey]===id)x[activeKey]=arr[0]||null}else{if(arr.length>=10)return toast('최대 10장까지 선택할 수 있습니다');arr.push(id);if(!x[activeKey])x[activeKey]=id}persist();renderStudio();renderPublish()}
function activateSlide(lang,id){const x=current();if(lang==='kr')x.krActive=id;else x.jpActive=id;persist();renderStudio()}
function frameFor(x,lang,id){const map=lang==='kr'?x.krFrames:x.jpFrames;if(!map[id])map[id]={z:1,x:0,y:0};return map[id]}
function activeId(x,lang){return lang==='kr'?x.krActive:x.jpActive}
function selectedIds(x,lang){return lang==='kr'?x.krSelected:x.jpSelected}
function pickFile(){$('#fileInput').click()}
$('#fileInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{const x=current(),id='up'+Date.now(),url=r.result;x.images.unshift({id,url,display:url,source:'upload'});if(x.images.length>10)x.images=x.images.slice(0,10);persist();renderStudio();toast('업로드 이미지가 후보에 추가됐습니다')};r.readAsDataURL(f);e.target.value=''})
function absoluteUrl(u,base){try{return new URL(u,base).href}catch{return ''}}
function proxy(url){if(!url||url.startsWith('data:')||url.includes('images.weserv.nl'))return url;return 'https://images.weserv.nl/?url='+encodeURIComponent(url.replace(/^https?:\/\//,''))+'&w=1600&h=2000&fit=inside&output=jpg'}
function queryText(x){return (x.title+' '+(x.captionKr||'').split('\n').slice(0,2).join(' ')).replace(/[#@]/g,' ').trim()}
async function autoFindImages(){const x=current();if(x.images.length>=8)return;await findImages(false)}
async function findImages(manual){const x=current(),input=$('#sourceInput');if(input)x.source=input.value.trim()||x.source;persist();const btn=$('#findBtn');if(btn){btn.disabled=true;btn.textContent='찾는 중'}try{let pool=[];if(x.source){try{const r=await fetch('https://api.microlink.io/?url='+encodeURIComponent(x.source));const j=await r.json();if(j?.data?.image?.url)pool.push({url:j.data.image.url,source:x.source,type:'article'})}catch{}try{const r=await fetch('https://api.allorigins.win/raw?url='+encodeURIComponent(x.source));if(r.ok){const html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html'),raw=[];doc.querySelectorAll('meta[property="og:image"],meta[name="twitter:image"]').forEach(m=>{if(m.content)raw.push(m.content)});doc.querySelectorAll('img').forEach(img=>{const u=img.currentSrc||img.getAttribute('data-src')||img.getAttribute('src');if(u)raw.push(u)});raw.slice(0,30).forEach(u=>pool.push({url:absoluteUrl(u,x.source),source:x.source,type:'article'}))}}catch{}}if(pool.length<10){try{const r=await fetch('https://api.openverse.org/v1/images/?q='+encodeURIComponent(queryText(x))+'&page_size=20');const j=await r.json();(j.results||[]).forEach(it=>{const u=it.thumbnail||it.url;if(u)pool.push({url:u,source:it.foreign_landing_url||it.detail_url||'',type:'search'})})}catch{}}const seen=new Set(),out=[];for(const p of pool){if(!p.url)continue;const key=p.url.split('?')[0];if(seen.has(key))continue;seen.add(key);out.push({id:'im'+Math.random().toString(36).slice(2),url:proxy(p.url),display:proxy(p.url),original:p.url,source:p.source,type:p.type});if(out.length===10)break}if(!out.length)throw new Error('none');x.images=out;x.krSelected=[];x.jpSelected=[];if(out[0]){x.krSelected=[out[0].id];x.jpSelected=[out[0].id];x.krActive=out[0].id;x.jpActive=out[0].id}x.krFrames={};x.jpFrames={};persist();renderStudio();renderPublish();toast(`${out.length}장 후보를 불러왔습니다`)}catch(e){if(manual)toast('자동 탐색 실패 · 업로드를 사용하세요')}finally{const b=$('#findBtn');if(b){b.disabled=false;b.textContent='이미지 10장 찾기'}}}
async function getImage(id){const x=current(),im=x.images.find(i=>i.id===id);if(!im)return null;if(runtime[id])return runtime[id];return new Promise(res=>{const z=new Image;z.crossOrigin='anonymous';z.onload=()=>{runtime[id]=z;res(z)};z.onerror=()=>res(null);z.src=im.display||im.url})}
function cover(ctx,im,w,h,f){const s=Math.max(w/im.width,h/im.height)*f.z,nw=im.width*s,nh=im.height*s;ctx.drawImage(im,(w-nw)/2+f.x,(h-nh)/2+f.y,nw,nh)}
async function drawAll(){await Promise.all([draw('kr'),draw('jp')])}
async function draw(lang,overrideId=null,exportCanvas=null,slideIndex=0){const x=current(),c=exportCanvas||document.getElementById(lang);if(!c)return;const id=overrideId||activeId(x,lang),im=await getImage(id),frame=id?frameFor(x,lang,id):{z:1,x:0,y:0};c.width=1080;c.height=1350;const ctx=c.getContext('2d');ctx.fillStyle='#111315';ctx.fillRect(0,0,1080,1350);if(im)cover(ctx,im,1080,1350,frame);else{ctx.fillStyle='#20252b';ctx.fillRect(0,0,1080,1350);ctx.fillStyle='rgba(255,255,255,.35)';ctx.textAlign='center';ctx.font='600 30px sans-serif';ctx.fillText('이미지를 선택하세요',540,675)}const grad=ctx.createLinearGradient(0,650,0,1350);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(.42,'rgba(0,0,0,.30)');grad.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=grad;ctx.fillRect(0,650,1080,700);ctx.fillStyle='#fff';ctx.textAlign='left';ctx.shadowColor='rgba(0,0,0,.58)';ctx.shadowBlur=18;const size=lang==='kr'?x.krFontSize:x.jpFontSize;ctx.font=`900 ${size}px -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif`;drawMultiline(ctx,lang==='kr'?x.headlineKr:x.headlineJp,72,970,930,size*1.18,5);ctx.shadowBlur=0;ctx.font='800 27px -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif';ctx.fillText('NO WAY THIS',72,1250);return c}
function drawMultiline(ctx,text,x,y,maxW,lh,maxLines){const lines=[];String(text||'').split('\n').forEach(p=>{if(!p.trim()){lines.push('');return}const words=p.includes(' ')?p.split(' '):[...p];let line='';words.forEach(w=>{const t=line?(p.includes(' ')?line+' '+w:line+w):w;if(ctx.measureText(t).width>maxW&&line){lines.push(line);line=w}else line=t});if(line)lines.push(line)});lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lh))}
function bindCanvas(lang){const c=document.getElementById(lang);if(!c||c.dataset.bound)return;c.dataset.bound='1';c.addEventListener('pointerdown',e=>{const id=activeId(current(),lang);if(!id)return;drag={lang,id,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag||drag.lang!==lang)return;const f=frameFor(current(),lang,drag.id);f.x+=(e.clientX-drag.x)*(1080/c.clientWidth);f.y+=(e.clientY-drag.y)*(1350/c.clientHeight);drag.x=e.clientX;drag.y=e.clientY;persist();draw(lang)});c.addEventListener('pointerup',()=>drag=null);c.addEventListener('pointerleave',()=>drag=null);c.addEventListener('wheel',e=>{e.preventDefault();const id=activeId(current(),lang);if(!id)return;const f=frameFor(current(),lang,id);f.z=Math.max(.7,Math.min(4,f.z+(e.deltaY<0?.08:-.08)));persist();draw(lang)},{passive:false})}
async function downloadSelected(lang){const x=current(),ids=selectedIds(x,lang);if(!ids.length)return toast(`${lang.toUpperCase()} 이미지를 먼저 선택하세요`);toast(`${ids.length}장 생성 중...`);for(let i=0;i<ids.length;i++){const c=document.createElement('canvas');await draw(lang,ids[i],c,i);const a=document.createElement('a');a.download=`noway_${x.id}_${lang}_${String(i+1).padStart(2,'0')}.png`;a.href=c.toDataURL('image/png');document.body.appendChild(a);a.click();a.remove();await new Promise(r=>setTimeout(r,260))}toast(`${lang.toUpperCase()} ${ids.length}장 저장 완료`)}
function openModal(){$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
$('#addBtn').onclick=openModal;$('#closeModal').onclick=closeModal;
$('#saveNew').onclick=()=>{const title=$('#newTitle').value.trim();if(!title)return toast('제목을 입력하세요');const kr=$('#newKr').value.trim()||title,jp=$('#newJp').value.trim()||kr,id='n'+Date.now();data.unshift(normalize([{id,title,source:$('#newSource').value.trim(),score:28,cat:'해외토픽',status:'HOLD',hooksKr:[kr,'',''],hooksJp:[jp,'',''],hook:0,headlineKr:kr,headlineJp:jp,captionKr:$('#newCapKr').value,captionJp:$('#newCapJp').value,music:['음원 후보 1','음원 후보 2','original audio'],fact:['원본 출처 확인','날짜 확인','핵심 사실 확인'],done:[],images:[]}])[0]);selected=id;closeModal();save();findImages(false)};
$$('.segments button').forEach(b=>b.onclick=()=>{$$('.segments button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderRadar()});
render();autoFindImages();