(()=>{
const TKEY='nwf-trash-v1',TARGET=12,INTERVAL=60*60*1000;
const KOREA_KNOWN_CELEBS=[
'cristiano ronaldo','ronaldo','호날두','lionel messi','messi','메시','david beckham','beckham','베컴',
'taylor swift','테일러 스위프트','justin bieber','저스틴 비버','selena gomez','셀레나 고메즈','ariana grande','아리아나 그란데','beyonce','beyoncé','비욘세','rihanna','리한나','lady gaga','레이디 가가','billie eilish','빌리 아일리시','bruno mars','브루노 마스','adele','아델','dua lipa','두아 리파','miley cyrus','마일리 사이러스','katy perry','케이티 페리','the weeknd','위켄드','ed sheeran','에드 시런','post malone','포스트 말론','harry styles','해리 스타일스','shawn mendes','션 멘데스','camila cabello','카밀라 카베요','nicki minaj','니키 미나즈','cardi b','카디 비','snoop dogg','스눕독','eminem','에미넴','drake','드레이크','travis scott','트래비스 스콧','dolly parton','돌리 파튼',
'tom cruise','톰 크루즈','brad pitt','브래드 피트','leonardo dicaprio','레오나르도 디카프리오','johnny depp','조니 뎁','robert downey jr','로버트 다우니 주니어','chris hemsworth','크리스 헴스워스','chris evans','크리스 에반스','ryan reynolds','라이언 레이놀즈','hugh jackman','휴 잭맨','keanu reeves','키아누 리브스','will smith','윌 스미스','dwayne johnson','the rock','드웨인 존슨','tom holland','톰 홀랜드','timothee chalamet','timothée chalamet','티모시 샬라메','zendaya','젠데이아','margot robbie','마고 로비','scarlett johansson','스칼렛 요한슨','angelina jolie','안젤리나 졸리','jennifer aniston','제니퍼 애니스톤','anne hathaway','앤 해서웨이','emma stone','엠마 스톤','emma watson','엠마 왓슨','natalie portman','나탈리 포트만','jennifer lawrence','제니퍼 로렌스','sydney sweeney','시드니 스위니','jenna ortega','제나 오르테가','millie bobby brown','밀리 바비 브라운',
'kim kardashian','킴 카다시안','kylie jenner','카일리 제너','kendall jenner','켄달 제너','paris hilton','패리스 힐튼','oprah winfrey','오프라 윈프리','elon musk','일론 머스크','mark zuckerberg','마크 저커버그','jeff bezos','제프 베이조스',
'jackie chan','성룡','jet li','이연걸','chow yun fat','주윤발','tony leung','양조위','andy lau','유덕화','stephen chow','주성치','donnie yen','견자단','takeshi kaneshiro','금성무'
];
function getTrash(){try{return JSON.parse(localStorage.getItem(TKEY))||[]}catch{return []}}
function norm(s=''){return String(s).toLowerCase().replace(/[^a-z0-9가-힣ぁ-んァ-ン一-龥éèêëáàâäíìîïóòôöúùûüçñ]+/g,' ').trim()}
function tokens(s=''){return new Set(norm(s).split(/\s+/).filter(w=>w.length>1))}
function similar(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return false;let n=0;A.forEach(x=>{if(B.has(x))n++});return n/Math.min(A.size,B.size)>=.65}
function isCelebrityItem(item){const cat=norm(item.cat||item.category||'');return /해외연예|연예|celebrity|entertainment|hollywood/.test(cat)}
function isKnownInKorea(item){if(!isCelebrityItem(item))return true;if(item.koreaAwareness===true||Number(item.koreaAwareness)>=4)return true;const hay=norm([item.title,item.titleKr,item.captionKr,item.person,item.celebrity].filter(Boolean).join(' '));return KOREA_KNOWN_CELEBS.some(name=>hay.includes(norm(name)))}
function blockedByMemo(item,trash){const memo=trash.flatMap(t=>[...(t.trashReasons||[]),t.trashMemo||'']).join(' ');if(/정치|사회성|정책/.test(memo)&&/(대통령|정부|국회|정책|선거|minister|president|election|government)/i.test(item.title))return true;if(/사진이 약|썸네일/.test(memo)&&item.visualScore&&item.visualScore<4)return true;return false}
function isBlocked(item){const t=getTrash();return !isKnownInKorea(item)||t.some(x=>(x.source&&item.source&&x.source===item.source)||norm(x.title)===norm(item.title)||similar(x.title,item.title))||blockedByMemo(item,t)}
function makeItem(r){const id='auto-'+(r.id||Date.now()+Math.random().toString(36).slice(2));const title=r.titleKr||r.title,hk=r.hookKr||title,hj=r.hookJp||'海外で話題\n何が起きた？';return normalize([{id,title,score:r.score||28,cat:r.cat||'해외토픽',status:'READY',source:r.source||'',publisher:r.publisher||'',publishedAt:r.publishedAt||'',hooksKr:[hk,r.hookKr2||title,'무슨 일이 있었나'],hooksJp:[hj,r.hookJp2||'何が起きたのか','現場が話題に'],hook:0,headlineKr:hk,headlineJp:hj,captionKr:r.captionKr||`${title}\n\n해외에서 새롭게 화제가 된 이슈입니다. 공개된 보도와 원문을 기준으로 핵심 상황과 배경을 확인한 뒤 게시할 수 있도록 READY에 자동 추가됐습니다.\n\n원문 출처와 날짜, 핵심 사실을 한 번 더 확인한 뒤 발행하세요.\n\n#NOWAYTHIS #해외토픽 #바이럴`,captionJp:r.captionJp||`海外で新たに話題になっているトピックです。\n\n公開情報をもとに、背景とポイントを確認してから投稿できるようREADYに追加されました。\n\n#NOWAYTHIS #海外ニュース #話題`,captionEn:r.captionEn||'',music:['original audio','trending audio','news audio'],fact:['원문 출처 확인','게시 날짜 확인','핵심 사실 교차 확인'],done:[],images:[],radarMeta:{scoreBreakdown:r.scoreBreakdown||null,thumbnailOptionsKr:r.thumbnailOptionsKr||[],thumbnailFinalKr:r.thumbnailFinalKr||'',photoCandidate:r.photoCandidate||'',photoSource:r.photoSource||'',layoutKr:r.layoutKr||'',ctaKr:r.ctaKr||'',factSources:r.factSources||[]}}])[0]}
async function fetchFeed(path){try{const res=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)return[];const v=await res.json();return Array.isArray(v)?v:[]}catch{return[]}}
async function syncRadar(){try{const [automation,latest,curated,regular]=await Promise.all([fetchFeed('radar-automation.json'),fetchFeed('curated-radar-auto-latest.json'),fetchFeed('curated-radar.json'),fetchFeed('radar-feed.json')]);const existing=data.map(x=>x.title);let add=[];
for(const r of [...latest,...automation,...curated]){if(!r?.title||isBlocked(r)||existing.some(t=>norm(t)===norm(r.title)||similar(t,r.title)))continue;add.push(makeItem(r));existing.push(r.title)}
let ready=data.filter(x=>x.status==='READY').length+add.length;for(const r of regular){if(ready>=TARGET)break;if(!r?.title||isBlocked(r)||existing.some(t=>norm(t)===norm(r.title)||similar(t,r.title)))continue;add.push(makeItem(r));existing.push(r.title);ready++}
if(add.length){data.push(...add);persist();render()}}catch(e){console.warn('radar sync',e)}}
window.syncRadarNow=syncRadar;setTimeout(syncRadar,1500);setInterval(syncRadar,INTERVAL);
})();