(()=>{
const LANG_STORE='nwf-active-language-v1';
const LANGS={
  kr:{label:'한국어',short:'KR',head:'headlineKr',hooks:'hooksKr',hook:'hookKr',caption:'captionKr',selected:'krSelected',active:'krActive',frames:'krFrames',font:'krFontSize',placeholder:'이미지를 선택하세요',copy:'복사',range:[350,650]},
  jp:{label:'日本語',short:'JP',head:'headlineJp',hooks:'hooksJp',hook:'hookJp',caption:'captionJp',selected:'jpSelected',active:'jpActive',frames:'jpFrames',font:'jpFontSize',placeholder:'画像を選択してください',copy:'コピー',range:[220,500]},
  en:{label:'English',short:'EN',head:'headlineEn',hooks:'hooksEn',hook:'hookEn',caption:'captionEn',selected:'enSelected',active:'enActive',frames:'enFrames',font:'enFontSize',placeholder:'Select an image',copy:'Copy',range:[300,700]}
};
let lang3=localStorage.getItem(LANG_STORE)||'kr';
if(!LANGS[lang3])lang3='kr';
function L(l=lang3){return LANGS[l]||LANGS.kr}
function isPostedLang(x,l){return !!x?.postedLangs?.[l]?.at}
function postingEvents(x){const out=[];Object.keys(LANGS).forEach(l=>{const e=x?.postedLangs?.[l];if(e?.at)out.push({lang:l,at:+e.at,slides:+e.slides||1})});if(x?.postedLegacyAt&&!out.length)out.push({lang:'legacy',at:+x.postedLegacyAt,slides:1});return out.filter(e=>Number.isFinite(e.at)&&e.at>0)}
function fmtTime(ts){const d=new Date(+ts),n=new Date(),same=d.toDateString()===n.toDateString();return same?`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`:`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function enCaptionFallback(x){return `${x.title}\n\nThis story is gaining attention online. Use the original source to verify what happened, when it happened, and the context behind the scene before publishing.\n\nFor a strong post, lead with the most surprising confirmed fact, then explain the key detail that the image alone cannot show. Avoid adding claims that are not supported by the source.\n\nWhat do you think about this story?\n\n#NOWAYTHIS #ViralNews #Trending`}
function ensureLang3(x){if(!x)return x;x.postedLangs=x.postedLangs||{};if(x.postedAt&&!x.postedLegacyAt&&!Object.keys(x.postedLangs).length)x.postedLegacyAt=+x.postedAt;const first=x.images?.[0]?.id||null;Object.entries(LANGS).forEach(([l,c])=>{if(!Array.isArray(x[c.selected]))x[c.selected]=[];x[c.selected]=x[c.selected].filter(id=>(x.images||[]).some(im=>im.id===id));if(x[c.active]&&!x[c.selected].includes(x[c.active]))x[c.active]=x[c.selected][0]||null;if(x[c.active]===undefined)x[c.active]=x[c.selected][0]||null;if(!x[c.frames]||typeof x[c.frames]!=='object')x[c.frames]={};if(!Number.isFinite(+x[c.font]))x[c.font]=70});x.hooksEn=Array.isArray(x.hooksEn)&&x.hooksEn.length?x.hooksEn:[x.title||'What happened?','The moment everyone noticed','Why this went viral'];x.headlineEn=x.headlineEn||x.hooksEn[0]||x.title||'';x.captionEn=x.captionEn||enCaptionFallback(x);x.hookKr=Number.isInteger(x.hookKr)?x.hookKr:(Number.isInteger(x.hook)?x.hook:0);x.hookJp=Number.isInteger(x.hookJp)?x.hookJp:(Number.isInteger(x.hook)?x.hook:0);x.hookEn=Number.isInteger(x.hookEn)?x.hookEn:0;if(first){Object.values(LANGS).forEach(c=>{if(!x[c.active]&&x[c.selected].length)x[c.active]=x[c.selected][0]})}return x}
data.forEach(ensureLang3);persist();
function sel(x,l){ensureLang3(x);return x[L(l).selected]}
function act(x,l){ensureLang3(x);return x[L(l).active]}
function frames(x,l){ensureLang3(x);return x[L(l).frames]}
function frame3(x,l,id){const m=frames(x,l);if(!m[id])m[id]={z:1,x:0,y:0};return m[id]}
function head(x,l){return x[L(l).head]||''}
function hooks(x,l){return x[L(l).hooks]||[]}
function font(x,l){return +x[L(l).font]||70}
function caption(x,l){return x[L(l).caption]||''}
window.setFactoryLanguage=function(l){if(!LANGS[l])return;lang3=l;localStorage.setItem(LANG_STORE,l);renderStudio();renderPublish()};
window.getFactoryLanguage=()=>lang3;
selectedIds=function(x,l){return sel(x,l)};activeId=function(x,l){return act(x,l)};frameFor=function(x,l,id){return frame3(x,l,id)};
setHook=function(i){const x=ensureLang3(current()),c=L();x[c.hook]=i;x[c.head]=(x[c.hooks]||[])[i]||x[c.head];persist();renderStudio();renderPublish()};
editHeadline=function(l,v){const x=ensureLang3(current());x[L(l).head]=v;persist();draw(l)};
setFontSize=function(l,v,out){const x=ensureLang3(current());x[L(l).font]=+v;if(out)out.textContent=+v+'px';persist();draw(l)};
editCaption=function(l,v){const x=ensureLang3(current());x[L(l).caption]=v;persist()};
copyCaption=function(l){navigator.clipboard.writeText(caption(ensureLang3(current()),l));toast(L(l).copy==='Copy'?'Caption copied':'캡션 복사 완료')};
toggleSelect=function(l,id){const x=ensureLang3(current()),c=L(l),arr=x[c.selected],i=arr.indexOf(id);if(i>=0){arr.splice(i,1);if(x[c.active]===id)x[c.active]=arr[0]||null}else{if(arr.length>=10)return toast('최대 10장까지 선택할 수 있습니다');arr.push(id);if(!x[c.active])x[c.active]=id}persist();renderStudio();renderPublish()};
activateSlide=function(l,id){const x=ensureLang3(current());x[L(l).active]=id;persist();renderStudio()};
function candidate3(x,l){const chosen=sel(x,l);if(!x.images?.length)return '<div class="candidate candidate-empty">사진 또는 영상 썸네일을 찾는 중입니다</div>';return x.images.slice(0,10).map((im,i)=>`<div class="candidate"><img src="${esc(im.display||im.url)}" alt="후보 ${i+1}"><span class="candidate-badge">${im.type==='video-poster'||im.type==='youtube'?'VIDEO':i+1}</span><div class="candidate-actions"><button class="${chosen.includes(im.id)?'selected':''}" onclick="toggleSelect('${l}','${im.id}')">${chosen.includes(im.id)?'선택됨':'선택'}</button></div></div>`).join('')}
function preview3(x,l){const c=L(l),ids=sel(x,l),active=act(x,l);return `<div class="preview-unit single-preview"><div class="selection-head"><div><b>${c.short}</b><span>${ids.length}장 선택</span></div><div class="slide-count">${active?ids.indexOf(active)+1:0}/${ids.length}</div></div><div class="card"><span class="lang">${c.short}</span><span class="drag-tip">drag · wheel</span><canvas id="${l}"></canvas></div><div class="selected-strip">${ids.length?ids.map((id,i)=>{const im=x.images.find(a=>a.id===id);return im?`<button class="slide-thumb ${id===active?'active':''}" onclick="activateSlide('${l}','${id}')"><img src="${esc(im.display||im.url)}"><span>${i+1}</span></button>`:''}).join(''):'<div class="no-selection">위 후보에서 이미지를 선택하세요</div>'}</div></div>`}
function font3(x,l){const v=font(x,l);return `<div class="font-control"><span>${L(l).short} 글자 크기</span><input type="range" min="42" max="110" step="2" value="${v}" oninput="setFontSize('${l}',this.value,this.nextElementSibling)"><output>${v}px</output></div>`}
function langBody(x,l){const c=L(l),hs=hooks(x,l),hi=Number.isInteger(x[c.hook])?x[c.hook]:0,posted=x.postedLangs?.[l];return `<div class="lang-body"><div class="source-hint lang-hint">${c.label} 작업만 표시 중입니다. 사진 선택·크롭·헤드라인·캡션·POSTING 기록은 다른 언어와 완전히 분리됩니다.</div><div class="candidate-grid">${candidate3(x,l)}</div>${preview3(x,l)}<div class="eyebrow">Headline</div><div class="hook-row">${hs.map((h,i)=>`<button class="${i===hi?'active':''}" onclick="setHook(${i})">${esc(String(h||'').replace(/\n/g,' / '))}</button>`).join('')}</div><textarea class="headline single-headline" oninput="editHeadline('${l}',this.value)" placeholder="${c.label} 헤드라인 · Enter로 줄바꿈">${esc(head(x,l))}</textarea>${font3(x,l)}<div class="download-row"><button class="soft" onclick="downloadSelected('${l}')">${c.short} ${sel(x,l).length}장 저장</button></div><div class="posting-action">${posted?.at?`<button class="posting-btn posted" disabled>${c.short} POSTED · ${fmtTime(posted.at)}</button>`:`<button class="posting-btn" onclick="markCurrentPosted('${l}')">${c.short} POSTING</button><span>Instagram 게시 완료 후 누르면 14 DAYS가 +1 됩니다.</span>`}</div></div>`}
function accordion3(x){return `<div class="language-accordion">${Object.entries(LANGS).map(([l,c])=>{const open=l===lang3,ev=x.postedLangs?.[l];return `<section class="lang-acc-item ${open?'open':''}"><button class="lang-acc-head" onclick="setFactoryLanguage('${l}')"><span><b>${c.label}</b><small>${c.short} · ${sel(x,l).length}장${ev?.at?' · POSTED':''}</small></span><i>${open?'−':'+'}</i></button>${open?langBody(x,l):''}</section>`}).join('')}</div>`}
renderStudio=function(){const x=ensureLang3(current());if(!x){$('#studio').innerHTML='';return}const events=postingEvents(x);$('#imageCount').textContent=`${x.images?.length||0} IMAGES · ${L().short} ${sel(x,lang3).length}`;const statusUi=events.length?`<span class="status status-static">POSTED</span>`:`<select class="status" onchange="changeStatus(this.value)"><option ${x.status==='READY'?'selected':''}>READY</option><option ${x.status==='HOLD'?'selected':''}>HOLD</option></select>`;$('#studio').innerHTML=`<div class="hero"><div><h2>${esc(x.title)}</h2><p>${esc(x.cat||'해외토픽')} · viral score ${x.score||28}/30</p></div>${statusUi}</div><div class="source-box"><div class="source-row"><input id="sourceInput" class="source-input" value="${esc(x.source||'')}" placeholder="기사·원본 URL"><button id="findBtn" class="primary" onclick="findImages(true)">이미지·영상 썸네일 찾기</button><button class="soft" onclick="pickFile()">업로드</button></div><div class="source-hint">사진 기사뿐 아니라 영상 기사도 대표 이미지, video poster, thumbnailUrl, YouTube 공식 썸네일까지 우선 수집합니다. 영상 자체가 아니라 정적 이미지 후보로 카드 제작합니다.</div></div>${accordion3(x)}`;requestAnimationFrame(()=>{draw(lang3);bindCanvas(lang3)})};
function metric3(l,t){const [min,max]=L(l).range,len=[...String(t||'')].length;return {len,min,max,label:len<min?'내용 부족':len>max?'조금 김':'적정',cls:len<min?'short':len>max?'long':'good',pct:Math.min(100,Math.round(len/min*100))}}
function formatCaption3(l){const x=ensureLang3(current()),c=L(l);let t=String(x[c.caption]||'').replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim();if(!t)return;const ctas={kr:'여러분은 이 이야기를 어떻게 보셨나요?',jp:'みなさんはこの話題をどう思いますか？',en:'What do you think about this story?'};if(!/[?？]\s*$/.test(t.replace(/(?:\s*#[^\s#]+)+\s*$/,'')))t+='\n\n'+ctas[l];x[c.caption]=t;persist();renderPublish();toast('캡션 구조를 정리했습니다')}
window.applyCaptionStructure3=formatCaption3;
renderPublish=function(){const x=ensureLang3(current());if(!x){$('#publish').innerHTML='';return}$('#publishState').textContent=postingEvents(x).length?'POSTED':x.status;const l=lang3,c=L(l),m=metric3(l,caption(x,l));const hist=postingEvents(x).map(e=>`<div class="posted-history-row"><span class="post-chip ${e.lang}">${e.lang==='legacy'?'POST':L(e.lang).short}</span><b>${e.slides}장</b><span>${fmtTime(e.at)}</span></div>`).join('');$('#publish').innerHTML=`<div class="section"><div class="section-head"><b>${c.short} CAPTION</b><button class="tiny" onclick="copyCaption('${l}')">${c.copy}</button></div><div class="caption-toolbar"><div class="caption-quality"><span class="caption-count">${m.len}자</span><span class="quality-pill ${m.cls}">${m.label}</span><span class="caption-rule">권장 ${m.min}~${m.max}자</span></div><button class="caption-format" onclick="applyCaptionStructure3('${l}')">구조 정리</button><div class="caption-progress" style="flex-basis:100%"><i style="width:${m.pct}%"></i></div></div><textarea class="caption" oninput="editCaption('${l}',this.value)">${esc(caption(x,l))}</textarea><div class="caption-tip"><b>실전 구조</b> · 첫줄 훅 → 사건 개요 → 핵심 디테일 → 확인된 맥락 → CTA → 해시태그</div></div><div class="section"><div class="section-head"><b>INSTAGRAM MUSIC</b><span class="muted-small">앱에서 선택</span></div>${(x.music||[]).map(mm=>`<div class="music"><span>${esc(mm)}</span><button class="tiny" onclick="copyInline('${esc(mm).replace(/'/g,"\\'")}')">복사</button></div>`).join('')}</div><div class="section"><div class="section-head"><b>FACT CHECK</b></div><div class="checks">${(x.fact||[]).map((f,i)=>`<label><input type="checkbox" ${x.done?.[i]?'checked':''} onchange="toggleFact(${i},this.checked)">${esc(f)}</label>`).join('')}</div></div>${hist?`<div class="section posted-history"><div class="section-head"><b>POSTED HISTORY</b></div><div class="posted-history-list">${hist}</div></div>`:''}`};
renderQuota=function(){const cutoff=Date.now()-14*864e5,events=data.flatMap(x=>postingEvents(ensureLang3(x))).filter(e=>e.at>=cutoff),n=events.length;$('#count14').textContent=n;$('#quotaBar').style.width=Math.min(100,n/150*100)+'%'};
const radarBeforeLang3=renderRadar;renderRadar=function(){radarBeforeLang3();if(filter==='POSTED'){const list=data.filter(x=>postingEvents(ensureLang3(x)).length);$('#radarList').innerHTML=list.length?list.map(x=>{const ev=postingEvents(x).sort((a,b)=>b.at-a.at);return `<div class="radar-item ${x.id===selected?'active':''}" onclick="selectItem('${x.id}')"><div class="radar-row"><div class="score">${x.score||28}</div><div class="radar-copy"><div class="radar-title">${esc(x.title)}</div><div class="radar-meta"><span class="dot POSTED"></span>POSTED · ${esc(x.cat||'해외토픽')}</div><div class="posted-meta">${ev.map(e=>`<span class="post-chip ${e.lang}">${e.lang==='legacy'?'POST':L(e.lang).short} · ${fmtTime(e.at)}</span>`).join('')}</div></div></div></div>`}).join(''):'<div class="empty-list">아직 POSTED 콘텐츠가 없습니다</div>'}};
window.markCurrentPosted=function(l=lang3){const x=ensureLang3(current()),c=L(l);if(isPostedLang(x,l))return toast(`${c.short}은 이미 POSTED 처리됐습니다`);const slides=sel(x,l).length;if(!slides)return toast(`${c.short} 이미지를 먼저 선택하세요`);const now=Date.now();x.postedLangs[l]={at:now,slides};x.postLog=x.postLog||[];x.postLog.push({lang:c.short,at:now,slides,type:'POSTING'});x.status='POSTED';x.postedAt=Math.max(...postingEvents(x).map(e=>e.at));persist();renderQuota();renderRadar();renderStudio();renderPublish();toast(`${c.short} POSTED · 14 DAYS +1`)};
changeStatus=function(v){const x=ensureLang3(current());if(postingEvents(x).length)return toast('게시 이력이 있는 콘텐츠는 POSTED 상태로 유지됩니다');x.status=v;save()};
async function getImage3(id){const x=ensureLang3(current()),im=x.images?.find(i=>i.id===id);if(!im)return null;if(runtime[id])return runtime[id];return new Promise(res=>{const z=new Image;z.crossOrigin='anonymous';z.onload=()=>{runtime[id]=z;res(z)};z.onerror=()=>res(null);z.src=im.display||im.url})}
drawAll=async function(){await draw(lang3)};draw=async function(l,overrideId=null,exportCanvas=null){const x=ensureLang3(current()),c=exportCanvas||document.getElementById(l);if(!c)return;const id=overrideId||act(x,l),im=await getImage3(id),f=id?frame3(x,l,id):{z:1,x:0,y:0};c.width=1080;c.height=1350;const ctx=c.getContext('2d');ctx.fillStyle='#111315';ctx.fillRect(0,0,1080,1350);if(im)cover(ctx,im,1080,1350,f);else{ctx.fillStyle='#20252b';ctx.fillRect(0,0,1080,1350);ctx.fillStyle='rgba(255,255,255,.35)';ctx.textAlign='center';ctx.font='600 30px sans-serif';ctx.fillText(L(l).placeholder,540,675)}const grad=ctx.createLinearGradient(0,650,0,1350);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(.42,'rgba(0,0,0,.30)');grad.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=grad;ctx.fillRect(0,650,1080,700);ctx.fillStyle='#fff';ctx.textAlign='left';ctx.shadowColor='rgba(0,0,0,.58)';ctx.shadowBlur=18;const sz=font(x,l);ctx.font=`900 ${sz}px -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif`;drawMultiline(ctx,head(x,l),72,970,930,sz*1.18,5);ctx.shadowBlur=0;ctx.font='800 27px -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif';ctx.fillText('NO WAY THIS',72,1250);return c};
bindCanvas=function(l){const c=document.getElementById(l);if(!c||c.dataset.bound)return;c.dataset.bound='1';c.addEventListener('pointerdown',e=>{const id=act(ensureLang3(current()),l);if(!id)return;drag={lang:l,id,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag||drag.lang!==l)return;const f=frame3(ensureLang3(current()),l,drag.id);f.x+=(e.clientX-drag.x)*(1080/c.clientWidth);f.y+=(e.clientY-drag.y)*(1350/c.clientHeight);drag.x=e.clientX;drag.y=e.clientY;persist();draw(l)});c.addEventListener('pointerup',()=>drag=null);c.addEventListener('pointerleave',()=>drag=null);c.addEventListener('wheel',e=>{e.preventDefault();const x=ensureLang3(current()),id=act(x,l);if(!id)return;const f=frame3(x,l,id);f.z=Math.max(.7,Math.min(4,f.z+(e.deltaY<0?.08:-.08)));persist();draw(l)},{passive:false})};
downloadSelected=async function(l){const x=ensureLang3(current()),ids=sel(x,l);if(!ids.length)return toast(`${L(l).short} 이미지를 먼저 선택하세요`);toast(`${ids.length}장 생성 중...`);for(let i=0;i<ids.length;i++){const c=document.createElement('canvas');await draw(l,ids[i],c);const a=document.createElement('a');a.download=`noway_${x.id}_${l}_${String(i+1).padStart(2,'0')}.png`;a.href=c.toDataURL('image/png');document.body.appendChild(a);a.click();a.remove();await new Promise(r=>setTimeout(r,260))}toast(`${L(l).short} ${ids.length}장 저장 완료`)};
function addPool(pool,u,source,type,base){try{const abs=base?new URL(u,base).href:u;if(abs)pool.push({url:abs,source,type})}catch{}}
function walkLd(v,pool,source){if(!v)return;if(Array.isArray(v)){v.forEach(z=>walkLd(z,pool,source));return}if(typeof v!=='object')return;['thumbnailUrl','contentUrl'].forEach(k=>{const z=v[k];if(typeof z==='string')addPool(pool,z,source,'video-poster',source)});const im=v.image;if(typeof im==='string')addPool(pool,im,source,'article',source);else if(im)walkLd(im,pool,source);Object.values(v).forEach(z=>{if(z&&typeof z==='object')walkLd(z,pool,source)})}
function youtubeThumb(src){try{const u=new URL(src);let id='';if(u.hostname.includes('youtube.com')){const m=u.pathname.match(/\/embed\/([^/?]+)/);id=m?.[1]||u.searchParams.get('v')||''}else if(u.hostname==='youtu.be')id=u.pathname.slice(1);return id?`https://i.ytimg.com/vi/${id}/maxresdefault.jpg`:''}catch{return ''}}
function query3(x){return `${x.title} ${head(x,lang3)} ${caption(x,lang3).split('\n').slice(0,2).join(' ')}`.replace(/[#@]/g,' ').trim()}
findImages=async function(manual){const x=ensureLang3(current()),input=$('#sourceInput');if(input)x.source=input.value.trim()||x.source;persist();const btn=$('#findBtn');if(btn){btn.disabled=true;btn.textContent='찾는 중'}try{let pool=[];if(x.source){try{const r=await fetch('https://api.microlink.io/?url='+encodeURIComponent(x.source));const j=await r.json();if(j?.data?.image?.url)addPool(pool,j.data.image.url,x.source,'article')}catch{}try{const r=await fetch('https://api.allorigins.win/raw?url='+encodeURIComponent(x.source));if(r.ok){const html=await r.text(),doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('meta[property="og:image"],meta[name="twitter:image"],meta[itemprop="thumbnailUrl"],link[rel="image_src"]').forEach(n=>addPool(pool,n.content||n.href,x.source,'article',x.source));doc.querySelectorAll('video[poster]').forEach(v=>addPool(pool,v.getAttribute('poster'),x.source,'video-poster',x.source));doc.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{try{walkLd(JSON.parse(s.textContent),pool,x.source)}catch{}});doc.querySelectorAll('iframe[src]').forEach(f=>{const t=youtubeThumb(f.src);if(t)addPool(pool,t,x.source,'youtube')});doc.querySelectorAll('img').forEach(img=>{const u=img.currentSrc||img.getAttribute('data-src')||img.getAttribute('src');if(u)addPool(pool,u,x.source,'article',x.source)})}}catch{}}if(pool.length<10){try{const r=await fetch('https://api.openverse.org/v1/images/?q='+encodeURIComponent(query3(x))+'&page_size=20');const j=await r.json();(j.results||[]).forEach(it=>{const u=it.thumbnail||it.url;if(u)addPool(pool,u,it.foreign_landing_url||it.detail_url||'','search')})}catch{}}const seen=new Set(),out=[];for(const p of pool){if(!p.url)continue;const key=p.url.split('?')[0];if(seen.has(key))continue;seen.add(key);out.push({id:'im'+Math.random().toString(36).slice(2),url:proxy(p.url),display:proxy(p.url),original:p.url,source:p.source,type:p.type});if(out.length===10)break}if(!out.length)throw new Error('none');x.images=out;Object.keys(LANGS).forEach(l=>{const c=L(l);x[c.selected]=out[0]?[out[0].id]:[];x[c.active]=out[0]?.id||null;x[c.frames]={}});persist();renderStudio();renderPublish();toast(`${out.length}장 후보를 불러왔습니다`)}catch(e){if(manual)toast('자동 탐색 실패 · 공식 영상 썸네일 또는 이미지를 직접 업로드하세요')}finally{const b=$('#findBtn');if(b){b.disabled=false;b.textContent='이미지·영상 썸네일 찾기'}}};
autoFindImages=async function(){const x=ensureLang3(current());if((x.images||[]).length>=8)return;await findImages(false)};
const saveBtn=document.getElementById('saveNew');if(saveBtn)saveBtn.onclick=()=>{const title=$('#newTitle').value.trim();if(!title)return toast('제목을 입력하세요');const kr=$('#newKr')?.value.trim()||title,jp=$('#newJp')?.value.trim()||kr,en=$('#newEn')?.value.trim()||title,id='n'+Date.now();const raw={id,title,source:$('#newSource').value.trim(),score:28,cat:'해외토픽',status:'HOLD',hooksKr:[kr,'',''],hooksJp:[jp,'',''],hooksEn:[en,'',''],hook:0,headlineKr:kr,headlineJp:jp,headlineEn:en,captionKr:$('#newCapKr')?.value||'',captionJp:$('#newCapJp')?.value||'',captionEn:$('#newCapEn')?.value||'',music:['음원 후보 1','음원 후보 2','original audio'],fact:['원본 출처 확인','날짜 확인','핵심 사실 확인'],done:[],images:[]};data.unshift(ensureLang3(normalize([raw])[0]));selected=id;$('#modal').classList.remove('open');save();findImages(false)};
render();
})();